language: ruby
sudo: false
cache: bundler
script: bundle exec rake spec
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.0
  - jruby
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
  fast_finish: true
